export { default as ClientController } from '@/core/controller/cliente.controller'
export { default as ExpedienteController } from '@/core/controller/expediente.controller'
export { default as FuerzaController } from '@/core/controller/fuerza.controller'
export { default as UserController } from '@/core/controller/user.controller'
export { default as ExpClienteController } from '@/core/controller/expcliente.controller'
export { default as MovimientoController } from '@/core/controller/movimientos.controller'