export { default as ClienteService } from '@/core/services/cliente.service'
export { default as ExpedienteService } from '@/core/services/expediente.service'
export { default as FuerzaService } from '@/core/services/fuerza.service'
export { default as UserService } from '@/core/services/user.service'
export { default as ExpclienteService } from '@/core/services/expcliente.service'
export { default as MovimientosService } from '@/core/services/movimientos.service'
export { default as ClientNotification } from '@/core/services/notification.service'